export const SET_EXPENSES = "SET_EXPENSES";
export const SET_LODING_TRUE = "SET_LODING_TRUE";
export const SET_LODING_FALSE = "SET_LODING_FALSE";
export const SET_SORTED_INFO = "SET_SORTED_INFO";
export const SET_FILTERED_INFO = "SET_FILTERED_INFO";
