export const SET_EXPENSES = "SET_EXPENSES";
export const SET_EXP_TABLE_LODING_TRUE = "SET_EXP_TABLE_LODING_TRUE";
export const SET_EXP_TABLE_LODING_FALSE = "SET_EXP_TABLE_LODING_FALSE";
export const SET_SORTED_INFO = "SET_SORTED_INFO";
export const SET_FILTERED_INFO = "SET_FILTERED_INFO";
export const SET_SHOWING_TABLE_TRUE = "SET_SHOWING_TABLE_TRUE";
export const SET_SHOWING_TABLE_FALSE = "SET_SHOWING_TABLE_FALSE";
export const SET_EXP_GR_ID = "SET_EXP_GR_ID";
