export const RESET_USER_ID = "RESET_USER_ID";
export const SET_USER = "SET_USER";
export const UPDATE_USER_EXP_GROUPS = "UPDATE_USER_EXP_GROUPS";
export const SHOW_SIGNUP_TRUE = "SHOW_SIGNUP_TRUE";
export const SHOW_SIGNUP_FALSE = "SHOW_SIGNUP_FALSE";
